-- --------------------------------------------------------
-- Host:                         Jalejandrorr.me
-- Versión del servidor:         5.5.59 - MySQL Community Server (GPL)
-- SO del servidor:              Linux
-- HeidiSQL Versión:             9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Volcando estructura de base de datos para ITZO
DROP DATABASE IF EXISTS `ITZO`;
CREATE DATABASE IF NOT EXISTS `ITZO` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `ITZO`;

-- Volcando estructura para tabla ITZO.ACTIVIDADES_COMPLEMENTARIAS
DROP TABLE IF EXISTS `ACTIVIDADES_COMPLEMENTARIAS`;
CREATE TABLE IF NOT EXISTS `ACTIVIDADES_COMPLEMENTARIAS` (
  `ID_ACTIVIDAD_COMPLEMENTARIA` int(11) NOT NULL,
  `ID_DEPARTAMENTO` int(11) DEFAULT NULL,
  `NOMBRE_ACTIVIDAD_COMPLEMENTARIA` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DESCRIPCION` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREDITOS` decimal(5,0) DEFAULT NULL,
  `HORAS` decimal(3,0) DEFAULT NULL,
  PRIMARY KEY (`ID_ACTIVIDAD_COMPLEMENTARIA`),
  KEY `FK_ACTIVIDA_REFERENCE_DEPARTAM` (`ID_DEPARTAMENTO`),
  CONSTRAINT `FK_ACTIVIDA_REFERENCE_DEPARTAM` FOREIGN KEY (`ID_DEPARTAMENTO`) REFERENCES `DEPARTAMENTOS` (`ID_DEPARTAMENTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.ACTIVIDADES_COMPLEMENTARIAS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ACTIVIDADES_COMPLEMENTARIAS` DISABLE KEYS */;
/*!40000 ALTER TABLE `ACTIVIDADES_COMPLEMENTARIAS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.ACTIVIDADES_DE_USUARIOS
DROP TABLE IF EXISTS `ACTIVIDADES_DE_USUARIOS`;
CREATE TABLE IF NOT EXISTS `ACTIVIDADES_DE_USUARIOS` (
  `ID_ACTIVIDAD_DE_USUARIO` int(11) NOT NULL,
  `NOMBRE` char(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_ACTIVIDAD_DE_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.ACTIVIDADES_DE_USUARIOS: ~1 rows (aproximadamente)
/*!40000 ALTER TABLE `ACTIVIDADES_DE_USUARIOS` DISABLE KEYS */;
INSERT INTO `ACTIVIDADES_DE_USUARIOS` (`ID_ACTIVIDAD_DE_USUARIO`, `NOMBRE`) VALUES
	(1, 'Administrador');
/*!40000 ALTER TABLE `ACTIVIDADES_DE_USUARIOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.ALUMNOS
DROP TABLE IF EXISTS `ALUMNOS`;
CREATE TABLE IF NOT EXISTS `ALUMNOS` (
  `ID_ALUMNO` int(11) NOT NULL,
  `ID_PERSONA` int(11) DEFAULT NULL,
  `ID_BECA` int(11) DEFAULT NULL,
  `ID_GRUPO_INDIGENA` int(11) DEFAULT NULL,
  `ID_MODALIDAD` int(11) DEFAULT NULL,
  `ID_SITUACION_ALUMNO` int(11) DEFAULT NULL,
  `ID_BACHILLERATO` int(11) DEFAULT NULL,
  `ID_USUARIO` int(11) DEFAULT NULL,
  `ID_CARRERA` int(11) DEFAULT NULL,
  `NOMBRE_BACHILLERATO` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PROMEDIO_BACHILLERATO` decimal(3,0) DEFAULT NULL,
  `MATRICULA` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FECHA_INSCRIPCION` smallint(6) DEFAULT NULL,
  `ACTA_NACIMIENTO` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CERTIFICADO_SECUNDARIA` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CARTA_BUENA_CONDUCTA` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CERTIFICADO_BACHILLERATO` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CURP` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DICTAMEN_REVALIDACION` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FORMA_FM9_EXTRANJERO` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `COMPROBANTE_PAGO` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CERTIFICADO_MEDICO` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `6_FOTOGRAFIAS_INFANTIL` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_ALUMNO`),
  KEY `FK_ALUMNOS_REFERENCE_MODALIDA` (`ID_MODALIDAD`),
  KEY `FK_ALUMNOS_REFERENCE_SITUACIO` (`ID_SITUACION_ALUMNO`),
  KEY `FK_ALUMNOS_REFERENCE_BACHILLE` (`ID_BACHILLERATO`),
  KEY `FK_ALUMNOS_REFERENCE_USUARIOS` (`ID_USUARIO`),
  KEY `FK_ALUMNOS_REFERENCE_CARRERAS` (`ID_CARRERA`),
  KEY `FK_ALUMNOS_REFERENCE_PERSONAS` (`ID_PERSONA`),
  KEY `FK_ALUMNOS_REFERENCE_BECAS` (`ID_BECA`),
  KEY `FK_ALUMNOS_REFERENCE_GRUPOS_I` (`ID_GRUPO_INDIGENA`),
  CONSTRAINT `FK_ALUMNOS_REFERENCE_BACHILLE` FOREIGN KEY (`ID_BACHILLERATO`) REFERENCES `BACHILLERATOS` (`ID_BACHILLERATO`),
  CONSTRAINT `FK_ALUMNOS_REFERENCE_BECAS` FOREIGN KEY (`ID_BECA`) REFERENCES `BECAS` (`ID_BECA`),
  CONSTRAINT `FK_ALUMNOS_REFERENCE_CARRERAS` FOREIGN KEY (`ID_CARRERA`) REFERENCES `CARRERAS` (`ID_CARRERA`),
  CONSTRAINT `FK_ALUMNOS_REFERENCE_GRUPOS_I` FOREIGN KEY (`ID_GRUPO_INDIGENA`) REFERENCES `GRUPOS_INDIGENAS` (`ID_GRUPO_INDIGENA`),
  CONSTRAINT `FK_ALUMNOS_REFERENCE_MODALIDA` FOREIGN KEY (`ID_MODALIDAD`) REFERENCES `MODALIDADES` (`ID_MODALIDAD`),
  CONSTRAINT `FK_ALUMNOS_REFERENCE_PERSONAS` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONAS` (`ID_PERSONA`),
  CONSTRAINT `FK_ALUMNOS_REFERENCE_SITUACIO` FOREIGN KEY (`ID_SITUACION_ALUMNO`) REFERENCES `SITUACION_ALUMNOS` (`ID_SITUACION_ALUMNO`),
  CONSTRAINT `FK_ALUMNOS_REFERENCE_USUARIOS` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIOS` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.ALUMNOS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ALUMNOS` DISABLE KEYS */;
/*!40000 ALTER TABLE `ALUMNOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.ALUMNOS_GRUPOS
DROP TABLE IF EXISTS `ALUMNOS_GRUPOS`;
CREATE TABLE IF NOT EXISTS `ALUMNOS_GRUPOS` (
  `ID_ALUMNOS_GRUPOS` int(11) NOT NULL,
  `ID_ALUMNO` int(11) DEFAULT NULL,
  `ID_GRUPO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_ALUMNOS_GRUPOS`),
  KEY `FK_ALUMNOS__REFERENCE_ALUMNOS` (`ID_ALUMNO`),
  KEY `FK_ALUMNOS__REFERENCE_GRUPOS` (`ID_GRUPO`),
  CONSTRAINT `FK_ALUMNOS__REFERENCE_ALUMNOS` FOREIGN KEY (`ID_ALUMNO`) REFERENCES `ALUMNOS` (`ID_ALUMNO`),
  CONSTRAINT `FK_ALUMNOS__REFERENCE_GRUPOS` FOREIGN KEY (`ID_GRUPO`) REFERENCES `GRUPOS` (`ID_GRUPO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.ALUMNOS_GRUPOS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ALUMNOS_GRUPOS` DISABLE KEYS */;
/*!40000 ALTER TABLE `ALUMNOS_GRUPOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.AREAS_DE_EMPRESAS
DROP TABLE IF EXISTS `AREAS_DE_EMPRESAS`;
CREATE TABLE IF NOT EXISTS `AREAS_DE_EMPRESAS` (
  `ID_AREA_DE_EMPRESA` int(11) NOT NULL,
  `NOMBRE` char(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TITULAR` char(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_AREA_DE_EMPRESA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.AREAS_DE_EMPRESAS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `AREAS_DE_EMPRESAS` DISABLE KEYS */;
/*!40000 ALTER TABLE `AREAS_DE_EMPRESAS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.BACHILLERATOS
DROP TABLE IF EXISTS `BACHILLERATOS`;
CREATE TABLE IF NOT EXISTS `BACHILLERATOS` (
  `ID_BACHILLERATO` int(11) NOT NULL,
  `ID_ESTADO` int(11) DEFAULT NULL,
  `ID_MUNICIPIO` int(11) DEFAULT NULL,
  `NOMBRE` char(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_BACHILLERATO`),
  KEY `FK_BACHILLE_REFERENCE_ESTADOS` (`ID_ESTADO`),
  KEY `FK_BACHILLE_REFERENCE_MUNICIPI` (`ID_MUNICIPIO`),
  CONSTRAINT `FK_BACHILLE_REFERENCE_ESTADOS` FOREIGN KEY (`ID_ESTADO`) REFERENCES `ESTADOS` (`ID_ESTADO`),
  CONSTRAINT `FK_BACHILLE_REFERENCE_MUNICIPI` FOREIGN KEY (`ID_MUNICIPIO`) REFERENCES `MUNICIPIOS` (`ID_MUNICIPIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.BACHILLERATOS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `BACHILLERATOS` DISABLE KEYS */;
/*!40000 ALTER TABLE `BACHILLERATOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.BECAS
DROP TABLE IF EXISTS `BECAS`;
CREATE TABLE IF NOT EXISTS `BECAS` (
  `ID_BECA` int(11) NOT NULL,
  `NOMBRE` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MONTO_BECA` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_BECA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.BECAS: ~2 rows (aproximadamente)
/*!40000 ALTER TABLE `BECAS` DISABLE KEYS */;
INSERT INTO `BECAS` (`ID_BECA`, `NOMBRE`, `MONTO_BECA`) VALUES
	(1, 'Subes', 2000),
	(2, 'Prospera', 4000);
/*!40000 ALTER TABLE `BECAS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.CALIFICACIONES
DROP TABLE IF EXISTS `CALIFICACIONES`;
CREATE TABLE IF NOT EXISTS `CALIFICACIONES` (
  `ID_CALIFICACION` int(11) NOT NULL,
  `ID_ALUMNOS_GRUPOS` int(11) DEFAULT NULL,
  `ID_MAESTRO` int(11) DEFAULT NULL,
  `ID_PERIODO` int(11) DEFAULT NULL,
  `ID_MATERIA` int(11) DEFAULT NULL,
  `ID_ALUMNO` int(11) DEFAULT NULL,
  `PARCIAL1` int(11) DEFAULT NULL,
  `FECHA_PARCIAL1` date DEFAULT NULL,
  `PARCIAL2` int(11) DEFAULT NULL,
  `FECHA_PARCIAL2` date DEFAULT NULL,
  `PARCIAL3` int(11) DEFAULT NULL,
  `FECHA_PARCIAL3` date DEFAULT NULL,
  `CALIFICACION_FINAL` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_CALIFICACION`),
  KEY `FK_CALIFICA_REFERENCE_ALUMNOS_` (`ID_ALUMNOS_GRUPOS`),
  KEY `FK_CALIFICA_REFERENCE_MAESTROS` (`ID_MAESTRO`),
  KEY `FK_CALIFICA_REFERENCE_PERIODOS` (`ID_PERIODO`),
  KEY `FK_CALIFICA_REFERENCE_MATERIAS` (`ID_MATERIA`),
  KEY `FK_CALIFICA_REFERENCE_ALUMNOS` (`ID_ALUMNO`),
  CONSTRAINT `FK_CALIFICA_REFERENCE_ALUMNOS` FOREIGN KEY (`ID_ALUMNO`) REFERENCES `ALUMNOS` (`ID_ALUMNO`),
  CONSTRAINT `FK_CALIFICA_REFERENCE_ALUMNOS_` FOREIGN KEY (`ID_ALUMNOS_GRUPOS`) REFERENCES `ALUMNOS_GRUPOS` (`ID_ALUMNOS_GRUPOS`),
  CONSTRAINT `FK_CALIFICA_REFERENCE_MAESTROS` FOREIGN KEY (`ID_MAESTRO`) REFERENCES `MAESTROS` (`ID_MAESTRO`),
  CONSTRAINT `FK_CALIFICA_REFERENCE_MATERIAS` FOREIGN KEY (`ID_MATERIA`) REFERENCES `MATERIAS` (`ID_MATERIA`),
  CONSTRAINT `FK_CALIFICA_REFERENCE_PERIODOS` FOREIGN KEY (`ID_PERIODO`) REFERENCES `PERIODOS` (`ID_PERIODO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.CALIFICACIONES: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `CALIFICACIONES` DISABLE KEYS */;
/*!40000 ALTER TABLE `CALIFICACIONES` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.CARRERAS
DROP TABLE IF EXISTS `CARRERAS`;
CREATE TABLE IF NOT EXISTS `CARRERAS` (
  `ID_CARRERA` int(11) NOT NULL,
  `ID_DIVISION_ACADEMICA` int(11) DEFAULT NULL,
  `ID_NIVEL_CARRERA` int(11) DEFAULT NULL,
  `ID_MODALIDAD` int(11) DEFAULT NULL,
  `NOMBRE_CARRERA` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DURACION_CARRERA` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SITUACION_CARRERA` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ESTRUCTURA_GENERICA` decimal(3,0) DEFAULT NULL,
  `ESPECIALIDAD` decimal(3,0) DEFAULT NULL,
  `RESIDENCIA_PROFESIONAL` decimal(3,0) DEFAULT NULL,
  `SERVICIO_SOCIAL` decimal(3,0) DEFAULT NULL,
  `ACTIVIDADES_COMPLEMENTARIAS` decimal(3,0) DEFAULT NULL,
  `TOTAL_DE_CREDITOS` decimal(3,0) DEFAULT NULL,
  PRIMARY KEY (`ID_CARRERA`),
  KEY `FK_CARRERAS_REFERENCE_DIVISION` (`ID_DIVISION_ACADEMICA`),
  KEY `FK_CARRERAS_REFERENCE_NIVELES_` (`ID_NIVEL_CARRERA`),
  KEY `FK_CARRERAS_REFERENCE_MODALIDA` (`ID_MODALIDAD`),
  CONSTRAINT `FK_CARRERAS_REFERENCE_DIVISION` FOREIGN KEY (`ID_DIVISION_ACADEMICA`) REFERENCES `DIVISIONES_ACADEMICAS` (`ID_DIVISION_ACADEMICA`),
  CONSTRAINT `FK_CARRERAS_REFERENCE_MODALIDA` FOREIGN KEY (`ID_MODALIDAD`) REFERENCES `MODALIDADES` (`ID_MODALIDAD`),
  CONSTRAINT `FK_CARRERAS_REFERENCE_NIVELES_` FOREIGN KEY (`ID_NIVEL_CARRERA`) REFERENCES `NIVELES_CARRERAS` (`ID_NIVEL_CARRERA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.CARRERAS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `CARRERAS` DISABLE KEYS */;
/*!40000 ALTER TABLE `CARRERAS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.CEDULAS_PROFESIONALES
DROP TABLE IF EXISTS `CEDULAS_PROFESIONALES`;
CREATE TABLE IF NOT EXISTS `CEDULAS_PROFESIONALES` (
  `ID_CEDULA_PROFESIONAL` int(11) NOT NULL,
  `ID_TIPO_CEDULA` int(11) DEFAULT NULL,
  `NOMBRE` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_CEDULA_PROFESIONAL`),
  KEY `FK_CEDULAS__REFERENCE_TIPOS_CE` (`ID_TIPO_CEDULA`),
  CONSTRAINT `FK_CEDULAS__REFERENCE_TIPOS_CE` FOREIGN KEY (`ID_TIPO_CEDULA`) REFERENCES `TIPOS_CEDULAS` (`ID_TIPO_CEDULA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.CEDULAS_PROFESIONALES: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `CEDULAS_PROFESIONALES` DISABLE KEYS */;
/*!40000 ALTER TABLE `CEDULAS_PROFESIONALES` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.DEPARTAMENTOS
DROP TABLE IF EXISTS `DEPARTAMENTOS`;
CREATE TABLE IF NOT EXISTS `DEPARTAMENTOS` (
  `ID_DEPARTAMENTO` int(11) NOT NULL,
  `NOMBRE` char(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_DEPARTAMENTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.DEPARTAMENTOS: ~1 rows (aproximadamente)
/*!40000 ALTER TABLE `DEPARTAMENTOS` DISABLE KEYS */;
INSERT INTO `DEPARTAMENTOS` (`ID_DEPARTAMENTO`, `NOMBRE`) VALUES
	(1, 'Sistemas');
/*!40000 ALTER TABLE `DEPARTAMENTOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.DIRECTORES_DIVISIONES
DROP TABLE IF EXISTS `DIRECTORES_DIVISIONES`;
CREATE TABLE IF NOT EXISTS `DIRECTORES_DIVISIONES` (
  `ID_DIRECTOR_DIVISION` char(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ID_PERSONA` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_DIRECTOR_DIVISION`),
  KEY `FK_DIRECTOR_REFERENCE_PERSONAS` (`ID_PERSONA`),
  CONSTRAINT `FK_DIRECTOR_REFERENCE_PERSONAS` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONAS` (`ID_PERSONA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.DIRECTORES_DIVISIONES: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `DIRECTORES_DIVISIONES` DISABLE KEYS */;
/*!40000 ALTER TABLE `DIRECTORES_DIVISIONES` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.DISCAPACIDADES
DROP TABLE IF EXISTS `DISCAPACIDADES`;
CREATE TABLE IF NOT EXISTS `DISCAPACIDADES` (
  `ID_DISCAPACIDAD` int(11) NOT NULL,
  `NOMBRE` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_DISCAPACIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.DISCAPACIDADES: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `DISCAPACIDADES` DISABLE KEYS */;
/*!40000 ALTER TABLE `DISCAPACIDADES` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.DISCAPACIDADES_ALUMNOS
DROP TABLE IF EXISTS `DISCAPACIDADES_ALUMNOS`;
CREATE TABLE IF NOT EXISTS `DISCAPACIDADES_ALUMNOS` (
  `ID_DISCAPACIDAD_ALUMNO` int(11) NOT NULL,
  `ID_ALUMNO` int(11) DEFAULT NULL,
  `ID_DISCAPACIDAD` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_DISCAPACIDAD_ALUMNO`),
  KEY `FK_DISCAPAC_REFERENCE_ALUMNOS` (`ID_ALUMNO`),
  KEY `FK_DISCAPAC_REFERENCE_DISCAPAC` (`ID_DISCAPACIDAD`),
  CONSTRAINT `FK_DISCAPAC_REFERENCE_ALUMNOS` FOREIGN KEY (`ID_ALUMNO`) REFERENCES `ALUMNOS` (`ID_ALUMNO`),
  CONSTRAINT `FK_DISCAPAC_REFERENCE_DISCAPAC` FOREIGN KEY (`ID_DISCAPACIDAD`) REFERENCES `DISCAPACIDADES` (`ID_DISCAPACIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.DISCAPACIDADES_ALUMNOS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `DISCAPACIDADES_ALUMNOS` DISABLE KEYS */;
/*!40000 ALTER TABLE `DISCAPACIDADES_ALUMNOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.DIVISIONES_ACADEMICAS
DROP TABLE IF EXISTS `DIVISIONES_ACADEMICAS`;
CREATE TABLE IF NOT EXISTS `DIVISIONES_ACADEMICAS` (
  `ID_DIVISION_ACADEMICA` int(11) NOT NULL,
  `ID_DIRECTOR_DIVISION` char(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NOMBRE` char(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_DIVISION_ACADEMICA`),
  KEY `FK_DIVISION_REFERENCE_DIRECTOR` (`ID_DIRECTOR_DIVISION`),
  CONSTRAINT `FK_DIVISION_REFERENCE_DIRECTOR` FOREIGN KEY (`ID_DIRECTOR_DIVISION`) REFERENCES `DIRECTORES_DIVISIONES` (`ID_DIRECTOR_DIVISION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.DIVISIONES_ACADEMICAS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `DIVISIONES_ACADEMICAS` DISABLE KEYS */;
/*!40000 ALTER TABLE `DIVISIONES_ACADEMICAS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.EMPRESAS
DROP TABLE IF EXISTS `EMPRESAS`;
CREATE TABLE IF NOT EXISTS `EMPRESAS` (
  `ID_EMPRESA` int(11) NOT NULL,
  `ID_GIRO_EMPRESARIAL` int(11) DEFAULT NULL,
  `ID_AREA_DE_EMPRESA` int(11) DEFAULT NULL,
  `ID_SECTOR_EMPRESARIAL` int(11) DEFAULT NULL,
  `ID_ESTADO` int(11) DEFAULT NULL,
  `ID_MUNICIPIO` int(11) DEFAULT NULL,
  `NOMBRE_EMPRESA` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RFC` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NOMBRE_COMERCIAL` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RAZON_SOCIAL` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADMINISTRADOR_EMPRESARIAL` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TELEFONO_LOCAL` decimal(10,0) DEFAULT NULL,
  `CALLE` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NUMERO` decimal(5,0) DEFAULT NULL,
  `CODIGO_POSTAL` decimal(5,0) DEFAULT NULL,
  `CIUDAD` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CORREO_ELECTRONICO` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_EMPRESA`),
  KEY `FK_EMPRESAS_REFERENCE_GIROS_EM` (`ID_GIRO_EMPRESARIAL`),
  KEY `FK_EMPRESAS_REFERENCE_AREAS_DE` (`ID_AREA_DE_EMPRESA`),
  KEY `FK_EMPRESAS_REFERENCE_SECTORES` (`ID_SECTOR_EMPRESARIAL`),
  KEY `FK_EMPRESAS_REFERENCE_ESTADOS` (`ID_ESTADO`),
  KEY `FK_EMPRESAS_REFERENCE_MUNICIPI` (`ID_MUNICIPIO`),
  CONSTRAINT `FK_EMPRESAS_REFERENCE_AREAS_DE` FOREIGN KEY (`ID_AREA_DE_EMPRESA`) REFERENCES `AREAS_DE_EMPRESAS` (`ID_AREA_DE_EMPRESA`),
  CONSTRAINT `FK_EMPRESAS_REFERENCE_ESTADOS` FOREIGN KEY (`ID_ESTADO`) REFERENCES `ESTADOS` (`ID_ESTADO`),
  CONSTRAINT `FK_EMPRESAS_REFERENCE_GIROS_EM` FOREIGN KEY (`ID_GIRO_EMPRESARIAL`) REFERENCES `GIROS_EMPRESARIALES` (`ID_GIRO_EMPRESARIAL`),
  CONSTRAINT `FK_EMPRESAS_REFERENCE_MUNICIPI` FOREIGN KEY (`ID_MUNICIPIO`) REFERENCES `MUNICIPIOS` (`ID_MUNICIPIO`),
  CONSTRAINT `FK_EMPRESAS_REFERENCE_SECTORES` FOREIGN KEY (`ID_SECTOR_EMPRESARIAL`) REFERENCES `SECTORES_EMPRESARIALES` (`ID_SECTOR_EMPRESARIAL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.EMPRESAS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `EMPRESAS` DISABLE KEYS */;
/*!40000 ALTER TABLE `EMPRESAS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.ESTADOS
DROP TABLE IF EXISTS `ESTADOS`;
CREATE TABLE IF NOT EXISTS `ESTADOS` (
  `ID_ESTADO` int(11) NOT NULL,
  `NOMBRE` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_ESTADO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.ESTADOS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ESTADOS` DISABLE KEYS */;
/*!40000 ALTER TABLE `ESTADOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.ESTADOS_CIVILES
DROP TABLE IF EXISTS `ESTADOS_CIVILES`;
CREATE TABLE IF NOT EXISTS `ESTADOS_CIVILES` (
  `ID_ESTADO_CIVIL` int(11) NOT NULL,
  `NOMBRE` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_ESTADO_CIVIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.ESTADOS_CIVILES: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ESTADOS_CIVILES` DISABLE KEYS */;
/*!40000 ALTER TABLE `ESTADOS_CIVILES` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.GIROS_EMPRESARIALES
DROP TABLE IF EXISTS `GIROS_EMPRESARIALES`;
CREATE TABLE IF NOT EXISTS `GIROS_EMPRESARIALES` (
  `ID_GIRO_EMPRESARIAL` int(11) NOT NULL,
  `NOMBRE` char(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_GIRO_EMPRESARIAL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.GIROS_EMPRESARIALES: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `GIROS_EMPRESARIALES` DISABLE KEYS */;
/*!40000 ALTER TABLE `GIROS_EMPRESARIALES` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.GRUPOS
DROP TABLE IF EXISTS `GRUPOS`;
CREATE TABLE IF NOT EXISTS `GRUPOS` (
  `ID_GRUPO` int(11) NOT NULL,
  `ID_CARRERA` int(11) DEFAULT NULL,
  `ID_PERIODO` int(11) DEFAULT NULL,
  `ID_DIVISION_ACADEMICA` int(11) DEFAULT NULL,
  `LETRA` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NUMERO_SEMESTRE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_GRUPO`),
  KEY `FK_GRUPOS_REFERENCE_CARRERAS` (`ID_CARRERA`),
  KEY `FK_GRUPOS_REFERENCE_PERIODOS` (`ID_PERIODO`),
  KEY `FK_GRUPOS_REFERENCE_DIVISION` (`ID_DIVISION_ACADEMICA`),
  CONSTRAINT `FK_GRUPOS_REFERENCE_CARRERAS` FOREIGN KEY (`ID_CARRERA`) REFERENCES `CARRERAS` (`ID_CARRERA`),
  CONSTRAINT `FK_GRUPOS_REFERENCE_DIVISION` FOREIGN KEY (`ID_DIVISION_ACADEMICA`) REFERENCES `DIVISIONES_ACADEMICAS` (`ID_DIVISION_ACADEMICA`),
  CONSTRAINT `FK_GRUPOS_REFERENCE_PERIODOS` FOREIGN KEY (`ID_PERIODO`) REFERENCES `PERIODOS` (`ID_PERIODO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.GRUPOS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `GRUPOS` DISABLE KEYS */;
/*!40000 ALTER TABLE `GRUPOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.GRUPOS_INDIGENAS
DROP TABLE IF EXISTS `GRUPOS_INDIGENAS`;
CREATE TABLE IF NOT EXISTS `GRUPOS_INDIGENAS` (
  `ID_GRUPO_INDIGENA` int(11) NOT NULL,
  `NOMBRE_GRUPO_INDIGENA` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_GRUPO_INDIGENA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.GRUPOS_INDIGENAS: ~11 rows (aproximadamente)
/*!40000 ALTER TABLE `GRUPOS_INDIGENAS` DISABLE KEYS */;
INSERT INTO `GRUPOS_INDIGENAS` (`ID_GRUPO_INDIGENA`, `NOMBRE_GRUPO_INDIGENA`) VALUES
	(1, 'Chontal'),
	(2, 'Maya'),
	(3, 'Nahuas'),
	(4, 'Zapotecas'),
	(5, 'Mixtecas'),
	(6, 'Otomíes'),
	(7, 'Totonacas'),
	(8, 'Tsotsiles'),
	(9, 'Zoques'),
	(10, 'Tarahumaras'),
	(11, 'Purépechas');
/*!40000 ALTER TABLE `GRUPOS_INDIGENAS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.GRUPO_MATERIAS
DROP TABLE IF EXISTS `GRUPO_MATERIAS`;
CREATE TABLE IF NOT EXISTS `GRUPO_MATERIAS` (
  `ID_GRUPO_MATERIA` int(11) NOT NULL,
  PRIMARY KEY (`ID_GRUPO_MATERIA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.GRUPO_MATERIAS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `GRUPO_MATERIAS` DISABLE KEYS */;
/*!40000 ALTER TABLE `GRUPO_MATERIAS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.LENGUAS_ALUMNOS
DROP TABLE IF EXISTS `LENGUAS_ALUMNOS`;
CREATE TABLE IF NOT EXISTS `LENGUAS_ALUMNOS` (
  `ID_LENGUA_ALUMNO` int(11) NOT NULL,
  `ID_ALUMNO` int(11) DEFAULT NULL,
  `ID_LENGUA_INDIGENA` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_LENGUA_ALUMNO`),
  KEY `FK_LENGUAS__REFERENCE_ALUMNOS` (`ID_ALUMNO`),
  KEY `FK_LENGUAS__REFERENCE_LENGUAS_` (`ID_LENGUA_INDIGENA`),
  CONSTRAINT `FK_LENGUAS__REFERENCE_ALUMNOS` FOREIGN KEY (`ID_ALUMNO`) REFERENCES `ALUMNOS` (`ID_ALUMNO`),
  CONSTRAINT `FK_LENGUAS__REFERENCE_LENGUAS_` FOREIGN KEY (`ID_LENGUA_INDIGENA`) REFERENCES `LENGUAS_INDIGENAS` (`ID_LENGUA_INDIGENA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.LENGUAS_ALUMNOS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `LENGUAS_ALUMNOS` DISABLE KEYS */;
/*!40000 ALTER TABLE `LENGUAS_ALUMNOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.LENGUAS_INDIGENAS
DROP TABLE IF EXISTS `LENGUAS_INDIGENAS`;
CREATE TABLE IF NOT EXISTS `LENGUAS_INDIGENAS` (
  `ID_LENGUA_INDIGENA` int(11) NOT NULL,
  `NOMBRE` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_LENGUA_INDIGENA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.LENGUAS_INDIGENAS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `LENGUAS_INDIGENAS` DISABLE KEYS */;
/*!40000 ALTER TABLE `LENGUAS_INDIGENAS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.MAESTROS
DROP TABLE IF EXISTS `MAESTROS`;
CREATE TABLE IF NOT EXISTS `MAESTROS` (
  `ID_MAESTRO` int(11) NOT NULL,
  `ID_CEDULA_PROFESIONAL` int(11) DEFAULT NULL,
  `ID_TIPO_CONTRATACION` int(11) DEFAULT NULL,
  `ID_PERSONA` int(11) DEFAULT NULL,
  `ID_USUARIO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_MAESTRO`),
  KEY `FK_MAESTROS_REFERENCE_CEDULAS_` (`ID_CEDULA_PROFESIONAL`),
  KEY `FK_MAESTROS_REFERENCE_TIPOS_CO` (`ID_TIPO_CONTRATACION`),
  KEY `FK_MAESTROS_REFERENCE_PERSONAS` (`ID_PERSONA`),
  KEY `FK_MAESTROS_REFERENCE_USUARIOS` (`ID_USUARIO`),
  CONSTRAINT `FK_MAESTROS_REFERENCE_CEDULAS_` FOREIGN KEY (`ID_CEDULA_PROFESIONAL`) REFERENCES `CEDULAS_PROFESIONALES` (`ID_CEDULA_PROFESIONAL`),
  CONSTRAINT `FK_MAESTROS_REFERENCE_PERSONAS` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONAS` (`ID_PERSONA`),
  CONSTRAINT `FK_MAESTROS_REFERENCE_TIPOS_CO` FOREIGN KEY (`ID_TIPO_CONTRATACION`) REFERENCES `TIPOS_CONTRATACIONES` (`ID_TIPO_CONTRATACION`),
  CONSTRAINT `FK_MAESTROS_REFERENCE_USUARIOS` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIOS` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.MAESTROS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `MAESTROS` DISABLE KEYS */;
/*!40000 ALTER TABLE `MAESTROS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.MATERIAS
DROP TABLE IF EXISTS `MATERIAS`;
CREATE TABLE IF NOT EXISTS `MATERIAS` (
  `ID_MATERIA` int(11) NOT NULL,
  `NOMBRE_MATERIA` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HORAS_TEORICAS` decimal(5,0) DEFAULT NULL,
  `HORAS_PRACTICAS` decimal(5,0) DEFAULT NULL,
  `HORAS_TOTALES` decimal(5,0) DEFAULT NULL,
  `CARACTERIZACION` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OBJETIVOS` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SEMESTRE` decimal(1,0) DEFAULT NULL,
  `CLAVE_IDENTIFICADORA` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_MATERIA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.MATERIAS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `MATERIAS` DISABLE KEYS */;
/*!40000 ALTER TABLE `MATERIAS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.MATERIA_GRUPO_MAESTRO
DROP TABLE IF EXISTS `MATERIA_GRUPO_MAESTRO`;
CREATE TABLE IF NOT EXISTS `MATERIA_GRUPO_MAESTRO` (
  `ID_MATERIA_GRUPO_MAESTRO` int(11) NOT NULL,
  `ID_MATERIA` int(11) DEFAULT NULL,
  `ID_GRUPO` int(11) DEFAULT NULL,
  `ID_MAESTRO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_MATERIA_GRUPO_MAESTRO`),
  KEY `FK_MATERIA__REFERENCE_MATERIAS` (`ID_MATERIA`),
  KEY `FK_MATERIA__REFERENCE_GRUPOS` (`ID_GRUPO`),
  KEY `FK_MATERIA__REFERENCE_MAESTROS` (`ID_MAESTRO`),
  CONSTRAINT `FK_MATERIA__REFERENCE_GRUPOS` FOREIGN KEY (`ID_GRUPO`) REFERENCES `GRUPOS` (`ID_GRUPO`),
  CONSTRAINT `FK_MATERIA__REFERENCE_MAESTROS` FOREIGN KEY (`ID_MAESTRO`) REFERENCES `MAESTROS` (`ID_MAESTRO`),
  CONSTRAINT `FK_MATERIA__REFERENCE_MATERIAS` FOREIGN KEY (`ID_MATERIA`) REFERENCES `MATERIAS` (`ID_MATERIA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.MATERIA_GRUPO_MAESTRO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `MATERIA_GRUPO_MAESTRO` DISABLE KEYS */;
/*!40000 ALTER TABLE `MATERIA_GRUPO_MAESTRO` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.MENU
DROP TABLE IF EXISTS `MENU`;
CREATE TABLE IF NOT EXISTS `MENU` (
  `cve_acceso` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Descripcion` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipo` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `img` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `url` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nivel` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Grupo` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Hijos` bit(1) NOT NULL,
  PRIMARY KEY (`cve_acceso`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.MENU: ~10 rows (aproximadamente)
/*!40000 ALTER TABLE `MENU` DISABLE KEYS */;
INSERT INTO `MENU` (`cve_acceso`, `Descripcion`, `tipo`, `img`, `url`, `nivel`, `Grupo`, `Hijos`) VALUES
	('1', 'Alumno', 'MODULO', '', '#', '0', 'ALUMNO', b'1'),
	('1.1', 'Calificaciones', 'Submodulo', '', '#', '1', 'ALUMNO', b'1'),
	('2', 'Administracion', 'MODULO', '', '#', '0', 'ADMIN', b'1'),
	('2.1', 'Usuarios', 'Submodulo', '', 'contenedor/usuarios.html', '1', 'ADMIN', b'0'),
	('2.2', 'Maestros', 'Submodulo', '', '#', '1', 'ADMIN', b'0'),
	('5', 'Catalogos', 'MODULO', '', '#', '0', 'CATALOGO', b'1'),
	('5.1', 'Grupos Indigenas', 'Submodulo', '', 'contenedor/grupos_indigenas.html', '1', 'CATALOGO', b'0'),
	('5.2', 'Becas', 'Submodulo', '', 'contenedor/becas.html', '1', 'CATALOGO', b'0'),
	('5.3', 'Modalidades', 'Submodulo', '', 'contenedor/modalidades.html', '1', 'CATALOGO', b'0'),
	('5.4', 'Situación Alumnos', 'Submodulo', '', 'contenedor/situacion_alumnos.html', '1', 'CATALOGO', b'0');
/*!40000 ALTER TABLE `MENU` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.MODALIDADES
DROP TABLE IF EXISTS `MODALIDADES`;
CREATE TABLE IF NOT EXISTS `MODALIDADES` (
  `ID_MODALIDAD` int(11) NOT NULL,
  `NOMBRE` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_MODALIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.MODALIDADES: ~1 rows (aproximadamente)
/*!40000 ALTER TABLE `MODALIDADES` DISABLE KEYS */;
INSERT INTO `MODALIDADES` (`ID_MODALIDAD`, `NOMBRE`) VALUES
	(1, 'Modalidad 1');
/*!40000 ALTER TABLE `MODALIDADES` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.MUNICIPIOS
DROP TABLE IF EXISTS `MUNICIPIOS`;
CREATE TABLE IF NOT EXISTS `MUNICIPIOS` (
  `ID_MUNICIPIO` int(11) NOT NULL,
  `ID_ESTADO` int(11) DEFAULT NULL,
  `NOMBRE` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_MUNICIPIO`),
  KEY `FK_MUNICIPI_REFERENCE_ESTADOS` (`ID_ESTADO`),
  CONSTRAINT `FK_MUNICIPI_REFERENCE_ESTADOS` FOREIGN KEY (`ID_ESTADO`) REFERENCES `ESTADOS` (`ID_ESTADO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.MUNICIPIOS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `MUNICIPIOS` DISABLE KEYS */;
/*!40000 ALTER TABLE `MUNICIPIOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.NIVELES_CARRERAS
DROP TABLE IF EXISTS `NIVELES_CARRERAS`;
CREATE TABLE IF NOT EXISTS `NIVELES_CARRERAS` (
  `ID_NIVEL_CARRERA` int(11) NOT NULL,
  `NOMBRE` char(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_NIVEL_CARRERA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.NIVELES_CARRERAS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `NIVELES_CARRERAS` DISABLE KEYS */;
/*!40000 ALTER TABLE `NIVELES_CARRERAS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.PERIODOS
DROP TABLE IF EXISTS `PERIODOS`;
CREATE TABLE IF NOT EXISTS `PERIODOS` (
  `ID_PERIODO` int(11) NOT NULL,
  `NOMBRE` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FECHA_INICIO` date DEFAULT NULL,
  `FECHA_TERMINO` date DEFAULT NULL,
  `DURACION_DIAS` int(11) DEFAULT NULL,
  `DURACION_MES` int(11) DEFAULT NULL,
  `MES_INICIO` date DEFAULT NULL,
  `MES_TERMINO` date DEFAULT NULL,
  `DIAS_FESTIVOS` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_PERIODO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.PERIODOS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `PERIODOS` DISABLE KEYS */;
/*!40000 ALTER TABLE `PERIODOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.PERSONAS
DROP TABLE IF EXISTS `PERSONAS`;
CREATE TABLE IF NOT EXISTS `PERSONAS` (
  `ID_PERSONA` int(11) NOT NULL,
  `ID_ESTADO` int(11) DEFAULT NULL,
  `ID_MUNICIPIO` int(11) DEFAULT NULL,
  `ID_TIPO_SANGUINEO` int(11) DEFAULT NULL,
  `ID_ESTADO_CIVIL` int(11) DEFAULT NULL,
  `ID_USUARIO` int(11) DEFAULT NULL,
  `ID_SEXO` int(11) DEFAULT NULL,
  `NOMBRE` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `APELLIDO_PATERNO` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `APELLIDO_MATERNO` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FECHA_NACIMIENTO` date DEFAULT NULL,
  `EDAD` int(11) DEFAULT NULL,
  `CALLE` char(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `COLONIA` char(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIUDAD` char(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODIGO_POSTAL` decimal(5,0) DEFAULT NULL,
  `TELEFONO_MOVIL` decimal(10,0) DEFAULT NULL,
  `TELEFONO_CASA` decimal(10,0) DEFAULT NULL,
  `CORREO_ELECTRONICO` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CURP` varchar(18) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RFC` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NSS` decimal(12,0) DEFAULT NULL,
  PRIMARY KEY (`ID_PERSONA`),
  KEY `FK_PERSONAS_REFERENCE_ESTADOS` (`ID_ESTADO`),
  KEY `FK_PERSONAS_REFERENCE_MUNICIPI` (`ID_MUNICIPIO`),
  KEY `FK_PERSONAS_REFERENCE_TIPOS_SA` (`ID_TIPO_SANGUINEO`),
  KEY `FK_PERSONAS_REFERENCE_USUARIOS` (`ID_USUARIO`),
  KEY `FK_PERSONAS_REFERENCE_ESTADOS_` (`ID_ESTADO_CIVIL`),
  KEY `FK_PERSONAS_REFERENCE_SEXOS` (`ID_SEXO`),
  CONSTRAINT `FK_PERSONAS_REFERENCE_ESTADOS` FOREIGN KEY (`ID_ESTADO`) REFERENCES `ESTADOS` (`ID_ESTADO`),
  CONSTRAINT `FK_PERSONAS_REFERENCE_ESTADOS_` FOREIGN KEY (`ID_ESTADO_CIVIL`) REFERENCES `ESTADOS_CIVILES` (`ID_ESTADO_CIVIL`),
  CONSTRAINT `FK_PERSONAS_REFERENCE_MUNICIPI` FOREIGN KEY (`ID_MUNICIPIO`) REFERENCES `MUNICIPIOS` (`ID_MUNICIPIO`),
  CONSTRAINT `FK_PERSONAS_REFERENCE_SEXOS` FOREIGN KEY (`ID_SEXO`) REFERENCES `SEXOS` (`ID_SEXO`),
  CONSTRAINT `FK_PERSONAS_REFERENCE_TIPOS_SA` FOREIGN KEY (`ID_TIPO_SANGUINEO`) REFERENCES `TIPOS_SANGUINEOS` (`ID_TIPO_SANGUINEO`),
  CONSTRAINT `FK_PERSONAS_REFERENCE_USUARIOS` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIOS` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.PERSONAS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `PERSONAS` DISABLE KEYS */;
/*!40000 ALTER TABLE `PERSONAS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.PLANES_DE_ESTUDIOS
DROP TABLE IF EXISTS `PLANES_DE_ESTUDIOS`;
CREATE TABLE IF NOT EXISTS `PLANES_DE_ESTUDIOS` (
  `ID_PLAN_DE_ESTUDIO` int(11) NOT NULL,
  `ID_CARRERA` int(11) DEFAULT NULL,
  `NOMBRE_PLAN_DE_ESTUDIO` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LETRA` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CLAVE_PLAN_DE_ESTUDIO` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ESTADO_DE_PLAN_DE_ESTUDIO` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ANO_PLAN_DE_ESTUDIO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_PLAN_DE_ESTUDIO`),
  KEY `FK_PLANES_D_REFERENCE_CARRERAS` (`ID_CARRERA`),
  CONSTRAINT `FK_PLANES_D_REFERENCE_CARRERAS` FOREIGN KEY (`ID_CARRERA`) REFERENCES `CARRERAS` (`ID_CARRERA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.PLANES_DE_ESTUDIOS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `PLANES_DE_ESTUDIOS` DISABLE KEYS */;
/*!40000 ALTER TABLE `PLANES_DE_ESTUDIOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.PLANES_DE_ESTUDIO_MATERIAS
DROP TABLE IF EXISTS `PLANES_DE_ESTUDIO_MATERIAS`;
CREATE TABLE IF NOT EXISTS `PLANES_DE_ESTUDIO_MATERIAS` (
  `ID_PLAN_DE_ESTUDIO_MATERIA` int(11) NOT NULL,
  `ID_PLAN_DE_ESTUDIO` int(11) DEFAULT NULL,
  `ID_MATERIA` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_PLAN_DE_ESTUDIO_MATERIA`),
  KEY `FK_PLANES_D_REFERENCE_PLANES_D` (`ID_PLAN_DE_ESTUDIO`),
  KEY `FK_PLANES_D_REFERENCE_MATERIAS` (`ID_MATERIA`),
  CONSTRAINT `FK_PLANES_D_REFERENCE_MATERIAS` FOREIGN KEY (`ID_MATERIA`) REFERENCES `MATERIAS` (`ID_MATERIA`),
  CONSTRAINT `FK_PLANES_D_REFERENCE_PLANES_D` FOREIGN KEY (`ID_PLAN_DE_ESTUDIO`) REFERENCES `PLANES_DE_ESTUDIOS` (`ID_PLAN_DE_ESTUDIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.PLANES_DE_ESTUDIO_MATERIAS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `PLANES_DE_ESTUDIO_MATERIAS` DISABLE KEYS */;
/*!40000 ALTER TABLE `PLANES_DE_ESTUDIO_MATERIAS` ENABLE KEYS */;

-- Volcando estructura para procedimiento ITZO.pLogin_B
DROP PROCEDURE IF EXISTS `pLogin_B`;
DELIMITER //
CREATE DEFINER=`JAlejandroRR`@`%` PROCEDURE `pLogin_B`(`user` VARCHAR(50), `pass` VARCHAR(50))
BEGIN
  SELECT CVE_ACCESO, DESCRIPCION, TIPO, IMG, URL, NIVEL, GRUPO, HIJOS FROM MENU;
END//
DELIMITER ;

-- Volcando estructura para procedimiento ITZO.pMENU_ACEESO_B
DROP PROCEDURE IF EXISTS `pMENU_ACEESO_B`;
DELIMITER //
CREATE DEFINER=`JAlejandroRR`@`%` PROCEDURE `pMENU_ACEESO_B`()
BEGIN SET @row_number = 0;
	SELECT CVE_ACCESO, DESCRIPCION, TIPO, IMG, URL, NIVEL, GRUPO, HIJOS, (@row_number:=@row_number + 1) AS num FROM MENU;
END//
DELIMITER ;

-- Volcando estructura para tabla ITZO.PUESTOS
DROP TABLE IF EXISTS `PUESTOS`;
CREATE TABLE IF NOT EXISTS `PUESTOS` (
  `ID_PUESTO` int(11) NOT NULL,
  `ID_DEPARTAMENTO` int(11) DEFAULT NULL,
  `NOMBRE` char(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_PUESTO`),
  KEY `FK_PUESTOS_REFERENCE_DEPARTAM` (`ID_DEPARTAMENTO`),
  CONSTRAINT `FK_PUESTOS_REFERENCE_DEPARTAM` FOREIGN KEY (`ID_DEPARTAMENTO`) REFERENCES `DEPARTAMENTOS` (`ID_DEPARTAMENTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.PUESTOS: ~1 rows (aproximadamente)
/*!40000 ALTER TABLE `PUESTOS` DISABLE KEYS */;
INSERT INTO `PUESTOS` (`ID_PUESTO`, `ID_DEPARTAMENTO`, `NOMBRE`) VALUES
	(1, 1, 'Gerente');
/*!40000 ALTER TABLE `PUESTOS` ENABLE KEYS */;

-- Volcando estructura para procedimiento ITZO.pUSUARIO_G
DROP PROCEDURE IF EXISTS `pUSUARIO_G`;
DELIMITER //
CREATE DEFINER=`JAlejandroRR`@`%` PROCEDURE `pUSUARIO_G`(
	IN `USER` VARCHAR(50),
	IN `PASS` VARCHAR(50)

)
BEGIN
INSERT INTO `ITZO`.`USUARIOS` (`ID_ROL`, `ID_ACTIVIDAD_DE_USUARIO`, `ID_PUESTO`, `NOMBRE_USUARIO`,`USUARIO_DE_ACCESO`, `CLAVE_DE_ACCESO`) VALUES ( '1', '1', '1', 'usuario2',USER,PASS);
select last_insert_id();
END//
DELIMITER ;

-- Volcando estructura para tabla ITZO.ROLES
DROP TABLE IF EXISTS `ROLES`;
CREATE TABLE IF NOT EXISTS `ROLES` (
  `ID_ROL` int(11) NOT NULL,
  `NOMBRE` char(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_ROL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.ROLES: ~1 rows (aproximadamente)
/*!40000 ALTER TABLE `ROLES` DISABLE KEYS */;
INSERT INTO `ROLES` (`ID_ROL`, `NOMBRE`) VALUES
	(1, 'ADMINISTRADOR');
/*!40000 ALTER TABLE `ROLES` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.ROLES_USUARIOS
DROP TABLE IF EXISTS `ROLES_USUARIOS`;
CREATE TABLE IF NOT EXISTS `ROLES_USUARIOS` (
  `ID_ROL_USUARIO` int(11) NOT NULL,
  PRIMARY KEY (`ID_ROL_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.ROLES_USUARIOS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ROLES_USUARIOS` DISABLE KEYS */;
/*!40000 ALTER TABLE `ROLES_USUARIOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.SECTORES_EMPRESARIALES
DROP TABLE IF EXISTS `SECTORES_EMPRESARIALES`;
CREATE TABLE IF NOT EXISTS `SECTORES_EMPRESARIALES` (
  `ID_SECTOR_EMPRESARIAL` int(11) NOT NULL,
  `NOMBRE` char(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_SECTOR_EMPRESARIAL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.SECTORES_EMPRESARIALES: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `SECTORES_EMPRESARIALES` DISABLE KEYS */;
/*!40000 ALTER TABLE `SECTORES_EMPRESARIALES` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.SEXOS
DROP TABLE IF EXISTS `SEXOS`;
CREATE TABLE IF NOT EXISTS `SEXOS` (
  `ID_SEXO` int(11) NOT NULL,
  `NOMBRE` char(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_SEXO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.SEXOS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `SEXOS` DISABLE KEYS */;
/*!40000 ALTER TABLE `SEXOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.SITUACION_ALUMNOS
DROP TABLE IF EXISTS `SITUACION_ALUMNOS`;
CREATE TABLE IF NOT EXISTS `SITUACION_ALUMNOS` (
  `ID_SITUACION_ALUMNO` int(11) NOT NULL,
  `NOMBRE` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_SITUACION_ALUMNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.SITUACION_ALUMNOS: ~4 rows (aproximadamente)
/*!40000 ALTER TABLE `SITUACION_ALUMNOS` DISABLE KEYS */;
INSERT INTO `SITUACION_ALUMNOS` (`ID_SITUACION_ALUMNO`, `NOMBRE`) VALUES
	(1, 'Situación 1'),
	(2, 'Situación 2'),
	(3, 'Situación 3'),
	(4, 'Situación X');
/*!40000 ALTER TABLE `SITUACION_ALUMNOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.SITUACION_DOCUMENTO
DROP TABLE IF EXISTS `SITUACION_DOCUMENTO`;
CREATE TABLE IF NOT EXISTS `SITUACION_DOCUMENTO` (
  `ID_SITUACION_DOCUMENTO` int(11) NOT NULL,
  `NOMBRE` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_SITUACION_DOCUMENTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.SITUACION_DOCUMENTO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `SITUACION_DOCUMENTO` DISABLE KEYS */;
/*!40000 ALTER TABLE `SITUACION_DOCUMENTO` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.TIPOS_CEDULAS
DROP TABLE IF EXISTS `TIPOS_CEDULAS`;
CREATE TABLE IF NOT EXISTS `TIPOS_CEDULAS` (
  `ID_TIPO_CEDULA` int(11) NOT NULL,
  `NOMBRE` char(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_CEDULA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.TIPOS_CEDULAS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `TIPOS_CEDULAS` DISABLE KEYS */;
/*!40000 ALTER TABLE `TIPOS_CEDULAS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.TIPOS_CONTRATACIONES
DROP TABLE IF EXISTS `TIPOS_CONTRATACIONES`;
CREATE TABLE IF NOT EXISTS `TIPOS_CONTRATACIONES` (
  `ID_TIPO_CONTRATACION` int(11) NOT NULL,
  `NOMBRE` char(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FECHA_INICIO` date DEFAULT NULL,
  `FECHA_TERMINO` date DEFAULT NULL,
  `SUELDO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_CONTRATACION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.TIPOS_CONTRATACIONES: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `TIPOS_CONTRATACIONES` DISABLE KEYS */;
/*!40000 ALTER TABLE `TIPOS_CONTRATACIONES` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.TIPOS_SANGUINEOS
DROP TABLE IF EXISTS `TIPOS_SANGUINEOS`;
CREATE TABLE IF NOT EXISTS `TIPOS_SANGUINEOS` (
  `ID_TIPO_SANGUINEO` int(11) NOT NULL,
  `NOMBRE` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_SANGUINEO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.TIPOS_SANGUINEOS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `TIPOS_SANGUINEOS` DISABLE KEYS */;
/*!40000 ALTER TABLE `TIPOS_SANGUINEOS` ENABLE KEYS */;

-- Volcando estructura para tabla ITZO.USUARIOS
DROP TABLE IF EXISTS `USUARIOS`;
CREATE TABLE IF NOT EXISTS `USUARIOS` (
  `ID_USUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `ID_ROL` int(11) DEFAULT NULL,
  `ID_ACTIVIDAD_DE_USUARIO` int(11) DEFAULT NULL,
  `ID_PUESTO` int(11) DEFAULT NULL,
  `NOMBRE_USUARIO` char(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USUARIO_DE_ACCESO` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CLAVE_DE_ACCESO` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  KEY `FK_USUARIOS_REFERENCE_ROLES` (`ID_ROL`),
  KEY `FK_USUARIOS_REFERENCE_ACTIVIDA` (`ID_ACTIVIDAD_DE_USUARIO`),
  KEY `FK_USUARIOS_REFERENCE_PUESTOS` (`ID_PUESTO`),
  CONSTRAINT `FK_USUARIOS_REFERENCE_ACTIVIDA` FOREIGN KEY (`ID_ACTIVIDAD_DE_USUARIO`) REFERENCES `ACTIVIDADES_DE_USUARIOS` (`ID_ACTIVIDAD_DE_USUARIO`),
  CONSTRAINT `FK_USUARIOS_REFERENCE_PUESTOS` FOREIGN KEY (`ID_PUESTO`) REFERENCES `PUESTOS` (`ID_PUESTO`),
  CONSTRAINT `FK_USUARIOS_REFERENCE_ROLES` FOREIGN KEY (`ID_ROL`) REFERENCES `ROLES` (`ID_ROL`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla ITZO.USUARIOS: ~30 rows (aproximadamente)
/*!40000 ALTER TABLE `USUARIOS` DISABLE KEYS */;
INSERT INTO `USUARIOS` (`ID_USUARIO`, `ID_ROL`, `ID_ACTIVIDAD_DE_USUARIO`, `ID_PUESTO`, `NOMBRE_USUARIO`, `USUARIO_DE_ACCESO`, `CLAVE_DE_ACCESO`) VALUES
	(1, 1, 1, 1, 'usuario2', 'x', 'x'),
	(2, 1, 1, 1, 'usuario2', '', ''),
	(3, 1, 1, 1, 'usuario2', '', ''),
	(4, 1, 1, 1, 'usuario2', '', ''),
	(5, 1, 1, 1, 'usuario2', '', ''),
	(6, 1, 1, 1, 'usuario2', '', ''),
	(7, 1, 1, 1, 'usuario2', '', ''),
	(8, 1, 1, 1, 'usuario2', 'anonimo', 'joselopez'),
	(9, 1, 1, 1, 'usuario2', 'anonimo', 'joselopez'),
	(10, 1, 1, 1, 'usuario2', 'anonimo', 'joselopez'),
	(11, 1, 1, 1, 'usuario2', 'anonimo', 'joselopez'),
	(12, 1, 1, 1, 'usuario2', 'anonimo', 'joselopez'),
	(13, 1, 1, 1, 'usuario2', 'anonimo', 'joselopez'),
	(14, 1, 1, 1, 'usuario2', 'anonimo', 'joselopez'),
	(15, 1, 1, 1, 'usuario2', 'anonimo', 'joselopez'),
	(16, 1, 1, 1, 'usuario2', 'anonimo', 'joselopez'),
	(17, 1, 1, 1, 'usuario2', 'anonimo', 'joselopez'),
	(18, 1, 1, 1, 'usuario2', 'anonimo', 'joselopez'),
	(19, 1, 1, 1, 'usuario2', 'anonimo', 'joselopez'),
	(20, 1, 1, 1, 'usuario2', 'anonimowdwadwadwadadwadwadw', 'joselopez'),
	(21, 1, 1, 1, 'usuario2', 'anonimowdwadwadwadadwadwadw', 'joselopezrhjgg'),
	(22, 1, 1, 1, 'usuario2', 'anonimoffawf', 'joselopez'),
	(23, 1, 1, 1, 'usuario2', 'anonimoffawf', 'joselopez'),
	(24, 1, 1, 1, 'usuario2', 'wadwad', 'dwadwadwa'),
	(25, 1, 1, 1, 'usuario2', '', ''),
	(26, 1, 1, 1, 'usuario2', '', ''),
	(27, 1, 1, 1, 'usuario2', 'anonimo', 'joselopez'),
	(28, 1, 1, 1, 'usuario2', 'anonimo', 'dwadwadwadadwjoselopez'),
	(29, 1, 1, 1, 'usuario2', 'anonimodwadwadwadwad', 'dwadwadwadadwjoselopez'),
	(30, 1, 1, 1, 'usuario2', 'anonimo', 'joselopez');
/*!40000 ALTER TABLE `USUARIOS` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
